{
 "title": "Electricity",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "accumulate_interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Mains Voltage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mains_voltage",
     "select": [
      [
       { "params": [ "volts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accumulated Usage (hourly)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "Accumulated Ch. $tag_channel",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "accumulated_energy",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"value\"))) FROM \"accumulated_energy\" WHERE $timeFilter GROUP BY time(1h), \"channel\" fill(previous) tz('UTC')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tz": "Africa/Johannesburg"
    }
   ]
  },
  {
   "title": "Live Power (w)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Live Power Ch. $tag_channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "live_power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accumulated Usage ($accumulate_interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "Accumulated Ch. $tag_channel",
     "groupBy": [
      { "params": [ "$accumulate_interval" ], "type": "time" },
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "accumulated_energy",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"value\"))) FROM \"accumulated_energy\" WHERE $timeFilter GROUP BY time($accumulate_interval), \"channel\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tz": "Africa/Johannesburg"
    }
   ]
  },
  {
   "title": "Accumulated Raw",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Accumulated Ch. $tag_channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "accumulated_energy",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Circuit Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": {
    "content": "<table>\n<thead>\n    <th>Circuit</th><th>Details</th>\n</thead>\n<tbody>\n    <tr><td>Total</td><td>Total Usage</td></tr>\n\t<tr><td>Plugs 1</td><td>Kitchen, Fridge</td></tr>\n\t<tr><td>Plugs 2</td><td>Kitchen, Kettle</td></tr>\n\t<tr><td>Plugs 3</td><td>Lounge, TV, UPS (And Office PCs on UPS)</td></tr>\n\t<tr><td>Plugs 4</td><td>Office, Rooms, Main bedroom plugs, Microwave in Kitchen, Pool plugs</td></tr>\n</tbody>\n</table>\n"
   }
  },
  {
   "title": "Accumulated Usage (kWh)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Accumulated Ch. $tag_channel",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "accumulated_energy",
     "query": "SELECT cumulative_sum(acc) FROM (SELECT non_negative_difference(value) AS acc FROM \"accumulated_energy\"  ) WHERE (\"channel\" =~ /^([1-9]|10)$/) AND $timeFilter GROUP BY \"channel\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "channel", "operator": ">", "value": "1" }
     ]
    }
   ]
  }
 ]
}